### ISSUE TITLE
Enable multi-pool client connections

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#398]
At the moment GatewayD supports a pair of connection pools for managing [available](https://github.com/gatewayd-io/gatewayd/blob/53d39ba358cc9d7f66aab0b1a052e8b1d90863ff/network/proxy.go#L41) and [busy](https://github.com/gatewayd-io/gatewayd/blob/53d39ba358cc9d7f66aab0b1a052e8b1d90863ff/network/proxy.go#L42) connections. On one hand, these pools enables many incoming client, limited by the capacity of the pools, to be connected to a single database server. On the other hand, each client connection is mapped to a single server connection. This works, but is not ideal.

The idea here is to let GatewayD connect to multiple databases at the same time per [configuration group](https://docs.gatewayd.io/miscellaneous/glossary/#configuration-group), aka. tenant. Each configuration group should have configuration for multiple [clients](https://docs.gatewayd.io/using-gatewayd/global-configuration/clients/), [pools](https://docs.gatewayd.io/using-gatewayd/global-configuration/pools/), [proxies](https://docs.gatewayd.io/using-gatewayd/global-configuration/proxies/) and a single [server](https://docs.gatewayd.io/using-gatewayd/global-configuration/servers/). Note that clients, pools and proxies have named groups, yet there will be a single server listening for all of these databases. The `distributionStrategy` and the `splitStrategy` config parameters of the server object will decide how the connection are routed to their corresponding database connections (clients).

This should eventually enable a range of possibilities including routing, switching and relaying, to name the least.

This is a possible task list:

- [x] Add a named config group (for clients, pools, proxies and servers) to config package to load the following config example
- [x] Connect to multiple databases based on the named client config groups
- [x] Create multiple pools per named config group and add corresponding clients to each pool
- [x] Create multiple proxies per named config group and connect them with each pool
- [x] Create a single server and attach all proxies to it
- [x] Add tests

This is what the global config _might_ look like after this change, yet other ideas should be explored.

```yaml
clients:
  default:
    active-writes: # <- This is the "named config group"
      network: tcp
      address: localhost:5432
      ...
    standby-reads:
      network: tcp
      address: localhost:5433
      ...

pools:
  default:
    active-writes:
      size: 10
    standby-reads:
      size: 10

proxies:
  default:
    active-writes:
      healthCheckPeriod: 60s
    standby-reads:
      healthCheckPeriod: 60s

servers:
  default:
    distributionStrategy: ab-testing, canary, write-read-split (?), round-robin, murmur-hash, etc.
    splitStrategy:
      active-writes: 90 # percent
      standby-reads: 10 # percent (automatically deduced)
    ...
```

## Related
- #55 

## Resources

- [Types of load balancing algorithms](https://www.cloudflare.com/learning/performance/types-of-load-balancing-algorithms/)
- [10 Load Balancing Techniques: Mastering the Art of Distributed Computing](https://vertisystem.medium.com/10-load-balancing-techniques-mastering-the-art-of-distributed-computing-9ab053ad138f)
- [Istio Traffic Management](https://istio.io/latest/docs/tasks/traffic-management/)
- [Linkerd Traffic Shifting](https://linkerd.io/2.15/tasks/traffic-shifting/)

**Comment by mostafa** [comment]
Hey @likecodingloveproblems,

Would you like to work on this feature? This enables a lot of possibilities.

**Comment by likecodingloveproblems** [comment]
Actually

**Comment by mostafa** [comment]
Awesome! :raised_hands:

**Comment by likecodingloveproblems** [comment]
I think this schema is correct not the above one:
@mostafa 
``` yaml
clients:
    active-writes: # <- This is the "named config group"
      network: tcp
      address: localhost:5432
      ...
    standby-reads:
      network: tcp
      address: localhost:5433
      ...

pools:
    active-writes:
      size: 10
    standby-reads:
      size: 10

proxies:
    active-writes:
      healthCheckPeriod: 60s
    standby-reads:
      healthCheckPeriod: 60s

servers:
  default:
    distributionStrategy: ab-testing, canary, write-read-split (?), round-robin, murmur-hash, etc.
    splitStrategy:
      active-writes: 90 # percent
      standby-reads: 10 # percent (automatically deduced)
    ...
```

**Comment by mostafa** [comment]
@likecodingloveproblems 
Now that I am rethinking it, it looks better the way you mentioned and also it'll be less nested. And then, the run command, and subsequently the server object, should be aware of non-matching set of config groups, especially in count and label, and then act accordingly based on the given parameters.

**Comment by likecodingloveproblems** [comment]
I try to draw the ERD.
Now I have two questions:
1. In the config file, we have a server object, we must relate proxies to servers as we want to have a one to many relation ship.
2. Now if a connection is closed or opened, we have OnOpen and OnClose functions on the **Server**, and get the server's **Proxy** and with a Map by O(1) the Connection is gotten, but now as the relation between **Server** and **Proxy** is becoming one to many, we must loop on all the proxies and then try to Find Connection's **Proxy**, Do you have any idea to have a better design?

**Comment by mostafa** [comment]
1. Correct.
2. We should figure out either 1) which proxy the connection wants to connect to or 2) which proxy the server wants to assign the connection to. Then we can store this information in a pool object inside the server, just like how available and busy connections work. Since the pool object is generic, the key can be the connection and the value can be the proxy it was assigned to.

**Comment by mostafa** [comment]
Hey @likecodingloveproblems,

I saw your awesome work you did in this [PR](https://github.com/gatewayd-io/gatewayd/pull/512). Is this still in progress?

**Comment by likecodingloveproblems** [comment]
Hi @mostafa 
Thanks for your interest.
yes, I am working on it in weekends :)

**Comment by mostafa** [comment]
Hey @likecodingloveproblems,

Any updates here?

**Comment by sinadarbouy** [comment]
@mostafa If I understand correctly, by removing nesting in clients, pools, and proxies, we can separate the server from the group of clients, pools, and proxies. This allows us to have two servers using the same proxy. Is that correct?

**Comment by mostafa** [comment]
@sinadarbouy No. The idea is to connect a single server instance to multiple proxies, each with different pools and different set of clients.

**Comment by sinadarbouy** [comment]
In [this PR](https://github.com/gatewayd-io/gatewayd/pull/577), we introduce a new configuration structure. We have separated the config groups for `clients`, `pools`, and `proxies`. This separation means we need to reference proxies in the server config groups to select proxies.

Additionally, we have implemented the default load balancer strategy, `ROUND_ROBIN`. To keep the scope of this PR manageable, the implementation for other `strategies` and `loadBalancingRules` will be addressed in separate PRs.

Here is the new configuration structure:
```yaml
# GatewayD Global Configuration

loggers:
  default:
...

metrics:
  default:
...

clients:
  default:
...
  default-2:
...

pools:
  default:
...
  default-2:
...

proxies:
  default:
...
  default-2:
...

servers:
  default:
    network: tcp
    address: 0.0.0.0:15432
    proxies:
      - "default"
      - "default-2"
    loadBalancer:
      strategy: ROUND_ROBIN
      # Not yet implemented.
      # loadBalancingRules:
      #   - condition: "default"
      #     percentages:
      #       - proxy: "default"
      #         percentage: 70
      #       - proxy: "default-2"
      #         percentage: 30

api:
...
```
